/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0 Hotfix 1
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................hardware.MappingUtil
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_HARDWARE_MAPPINGUTIL_AUTOMATIC_H_
#define _ASD_HARDWARE_MAPPINGUTIL_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/* SERAP structure for hardware_MappingUtil_Automatic intentionally not created */
/* reason: no local parameters                                                */




/* component structure for class HARDWARE_MAPPINGUTIL_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .............hardware_MappingUtil_Automatic */
#define _hardware_MappingUtil_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class hardware_MappingUtil_Automatic
 ******************************************************************************/
extern float32 hardware_MappingUtil_Automatic_map (
   /* IN    */ const float32 x,
   /* IN    */ const float32 in_min,
   /* IN    */ const float32 in_max,
   /* IN    */ const float32 out_min,
   /* IN    */ const float32 out_max
   );


/* BEGIN: extern declarations for SERAP */
/* END: extern declarations for SERAP */



#endif /* _ASD_HARDWARE_MAPPINGUTIL_AUTOMATIC_H_ */
