/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0 Hotfix 1
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................hardware.HandDistanceSensor
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_HARDWARE_HANDDISTANCESENSOR_AUTOMATIC_H_
#define _ASD_HARDWARE_HANDDISTANCESENSOR_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "hardware_MappingUtil_Automatic.h"

/******************************************************************************
 * BEGIN: DEFINITION OF SERAP STRUCT FOR MODULE 'hardware_HandDistanceSensor_Automatic'
 * ---------------------------------------------------------------------------*/
struct PTR_HARDWARE_HANDDISTANCESENSOR_AUTOMATIC {
   const volatile float32 * adcMax;
   const volatile float32 * adcMin;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SERAP STRUCT FOR MODULE 'hardware_HandDistanceSensor_Automatic'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'hardware_HandDistanceSensor_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct hardware_HandDistanceSensor_Automatic_CAL_MEM_SUBSTRUCT {
   float32 adcMax;
   float32 adcMin;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'hardware_HandDistanceSensor_Automatic'
 ******************************************************************************/


/* component structure for module HARDWARE_HANDDISTANCESENSOR_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ......hardware_HandDistanceSensor_Automatic */
#define _hardware_HandDistanceSensor_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'hardware_HandDistanceSensor_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern const volatile struct hardware_HandDistanceSensor_Automatic_CAL_MEM_SUBSTRUCT hardware_HandDistanceSensor_CAL_MEM;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module hardware_HandDistanceSensor_Automatic
 ******************************************************************************/
extern void hardware_HandDistanceSensor_Automatic_read (void);


/* BEGIN: extern declarations for SERAP */
extern const volatile struct PTR_hardware_HandDistanceSensor_Automatic _SERAP_REF_hardware_HandDistanceSensor;

extern const volatile struct PTR_hardware_HandDistanceSensor_Automatic _SERAP_WORK_hardware_HandDistanceSensor;

/* END: extern declarations for SERAP */



#endif /* _ASD_HARDWARE_HANDDISTANCESENSOR_AUTOMATIC_H_ */
