/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0 Hotfix 1
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................model.MainClass
 * REPRESENTATION:..............stm32f334r8
 * DESCRIPTION:
 *    
 ******************************************************************************/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "model_MainClass_stm32f334r8.h"
#include "model_RgbLed_stm32f334r8.h"
#include "model_Signals_stm32f334r8.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'model_MainClass'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: SERAP (definition of data structures)
 * ---------------------------------------------------------------------------*/
/* ----------------------------------------------------------------------------
 * END: SERAP (definition of data structures)
 ******************************************************************************/




/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'model_MainClass_stm32f334r8_step'
 * ----------------------------------------------------------------------------
 * model name:...................................'step'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */
#define model_Signals_autoModeButton__model_MainClass_stm32f334r8_step (model_Signals_autoModeButton)
#define model_Signals_ballPosition__model_MainClass_stm32f334r8_step (model_Signals_ballPosition)
#define model_Signals_handPosition__model_MainClass_stm32f334r8_step (model_Signals_handPosition)
#define model_Signals_ledRing__model_MainClass_stm32f334r8_step (model_Signals_ledRing)
#define model_Signals_score__model_MainClass_stm32f334r8_step (model_Signals_score)
#define model_Signals_servoPosition__model_MainClass_stm32f334r8_step (model_Signals_servoPosition)
#define model_Signals_startGameButton__model_MainClass_stm32f334r8_step (model_Signals_startGameButton)


void model_MainClass_stm32f334r8_step (void)
{
   esdl_gameController_model_MainClass_RAM.ballPosition = model_Signals_ballPosition__model_MainClass_stm32f334r8_step;
   esdl_gameController_model_MainClass_RAM.startGame
      = model_Signals_startGameButton__model_MainClass_stm32f334r8_step;
   model_GameController_Automatic_periodicTrigger();
   model_Signals_score__model_MainClass_stm32f334r8_step = esdl_gameController_model_MainClass_RAM.score;
   esdl_ledController_model_MainClass_RAM.gameTime = model_GameController_Automatic_getTime();
   esdl_ledController_model_MainClass_RAM.gameState = model_GameController_Automatic_gameState();
   model_LedController_stm32f334r8_periodicTrigger();
   memcpy(model_Signals_ledRing__model_MainClass_stm32f334r8_step , esdl_ledController_model_MainClass_RAM.ledRing , sizeof(struct model_RgbLed_stm32f334r8[12]));
   esdl_servoController_model_MainClass_RAM.gameState = model_GameController_Automatic_gameState();
   esdl_servoController_model_MainClass_RAM.ballPosition = model_Signals_ballPosition__model_MainClass_stm32f334r8_step;
   esdl_servoController_model_MainClass_RAM.handPosition = model_Signals_handPosition__model_MainClass_stm32f334r8_step;
   esdl_servoController_model_MainClass_RAM.switchMode
      = model_Signals_autoModeButton__model_MainClass_stm32f334r8_step;
   model_ServoController_Automatic_periodicTrigger();
   model_Signals_servoPosition__model_MainClass_stm32f334r8_step = esdl_servoController_model_MainClass_RAM.servoPosition;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'model_MainClass_stm32f334r8_step'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



