/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0 Hotfix 1
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................model.ServoController
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MODEL_SERVOCONTROLLER_AUTOMATIC_H_
#define _ASD_MODEL_SERVOCONTROLLER_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "SystemLib_Miscellaneous_EdgeRising_Impl.h"

/******************************************************************************
 * BEGIN: DEFINITION OF SERAP STRUCT FOR CLASS 'model_ServoController_Automatic'
 * ---------------------------------------------------------------------------*/
struct PTR_MODEL_SERVOCONTROLLER_AUTOMATIC {
   const volatile float32 * kd;
   const volatile float32 * ki;
   const volatile float32 * kp;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SERAP STRUCT FOR CLASS 'model_ServoController_Automatic'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'model_ServoController_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct model_ServoController_Automatic_CAL_MEM_SUBSTRUCT {
   float32 kd;
   float32 ki;
   float32 kp;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'model_ServoController_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'model_ServoController_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct model_ServoController_Automatic_RAM_SUBSTRUCT {
   float32 ballPosition;
   float32 error;
   float32 handPosition;
   float32 integral;
   float32 lastValue;
   float32 servoPosition;
   boolean doIntegrate;
   uint8 gameState;
   uint8 sm;
   boolean switchMode;
   struct SystemLib_Miscellaneous_EdgeRising_Impl_RAM_SUBSTRUCT edgeDetect;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'model_ServoController_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'model_ServoController_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct model_ServoController_Automatic {
   struct SystemLib_Miscellaneous_EdgeRising_Impl edgeDetect;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'model_ServoController_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ............model_ServoController_Automatic */
#define _model_ServoController_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'esdl_servoController_model_MainClass_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern const volatile struct model_ServoController_Automatic_CAL_MEM_SUBSTRUCT esdl_servoController_model_MainClass_CAL_MEM;

/* forward declaration of substruct variable 'esdl_servoController_model_MainClass_RAM' */
/* containing 'RAM' memory class tree */
extern struct model_ServoController_Automatic_RAM_SUBSTRUCT esdl_servoController_model_MainClass_RAM;

/* forward declaration of component variable 'esdl_servoController_model_MainClass' */
/* containing 'ROM' memory class tree */
extern const struct model_ServoController_Automatic esdl_servoController_model_MainClass;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by class model_ServoController_Automatic
 ******************************************************************************/
extern void model_ServoController_Automatic_autoMode (void);
boolean model_ServoController_Automatic_isGameIdle (void);
boolean model_ServoController_Automatic_isGameRunning (void);
extern void model_ServoController_Automatic_periodicTrigger (void);
boolean model_ServoController_Automatic_switchModeButtonPushed (void);


/* BEGIN: extern declarations for SERAP */
extern const volatile struct PTR_model_ServoController_Automatic _SERAP_REF_esdl_servoController_model_MainClass;

extern const volatile struct PTR_model_ServoController_Automatic _SERAP_WORK_esdl_servoController_model_MainClass;

/* END: extern declarations for SERAP */



#endif /* _ASD_MODEL_SERVOCONTROLLER_AUTOMATIC_H_ */
