/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0 Hotfix 1
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................model.LedController
 * REPRESENTATION:..............stm32f334r8
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "model_LedController_stm32f334r8.h"
#include "model_RgbLed_stm32f334r8.h"
/******************************************************************************
 * BEGIN: source code of a single instance class
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'esdl_ledController_model_MainClass_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'ledController'
 * data set:.....................................'MODEL_LEDCONTROLLER_STM32F334R8_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct model_LedController_stm32f334r8_RAM_SUBSTRUCT esdl_ledController_model_MainClass_RAM = {
   /* struct element:'esdl_ledController_model_MainClass_RAM.fadeValue' (modeled as:'fadeValue.ledController') */
   0.0F,
   /* struct element:'esdl_ledController_model_MainClass_RAM.gameTime' (modeled as:'gameTime.ledController') */
   0.0F,
   /* struct element:'esdl_ledController_model_MainClass_RAM.gameState' (modeled as:'gameState.ledController') */
   0U,
   /* struct element:'esdl_ledController_model_MainClass_RAM.sm' (modeled as:'sm.ledController') */
   0U /* IdleFading */,
   /* substruct: esdl_ledController_model_MainClass_RAM.ledRing (modeled as:'ledRing.ledController') */
   {
      {
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[0].blue' (modeled as:'blue.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[0].green' (modeled as:'green.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[0].red' (modeled as:'red.ledRing.ledController') */
         0U
      },
      {
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[1].blue' (modeled as:'blue.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[1].green' (modeled as:'green.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[1].red' (modeled as:'red.ledRing.ledController') */
         0U
      },
      {
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[2].blue' (modeled as:'blue.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[2].green' (modeled as:'green.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[2].red' (modeled as:'red.ledRing.ledController') */
         0U
      },
      {
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[3].blue' (modeled as:'blue.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[3].green' (modeled as:'green.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[3].red' (modeled as:'red.ledRing.ledController') */
         0U
      },
      {
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[4].blue' (modeled as:'blue.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[4].green' (modeled as:'green.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[4].red' (modeled as:'red.ledRing.ledController') */
         0U
      },
      {
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[5].blue' (modeled as:'blue.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[5].green' (modeled as:'green.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[5].red' (modeled as:'red.ledRing.ledController') */
         0U
      },
      {
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[6].blue' (modeled as:'blue.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[6].green' (modeled as:'green.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[6].red' (modeled as:'red.ledRing.ledController') */
         0U
      },
      {
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[7].blue' (modeled as:'blue.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[7].green' (modeled as:'green.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[7].red' (modeled as:'red.ledRing.ledController') */
         0U
      },
      {
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[8].blue' (modeled as:'blue.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[8].green' (modeled as:'green.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[8].red' (modeled as:'red.ledRing.ledController') */
         0U
      },
      {
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[9].blue' (modeled as:'blue.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[9].green' (modeled as:'green.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[9].red' (modeled as:'red.ledRing.ledController') */
         0U
      },
      {
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[10].blue' (modeled as:'blue.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[10].green' (modeled as:'green.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[10].red' (modeled as:'red.ledRing.ledController') */
         0U
      },
      {
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[11].blue' (modeled as:'blue.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[11].green' (modeled as:'green.ledRing.ledController') */
         0U,
         /* struct element:'esdl_ledController_model_MainClass_RAM.ledRing[11].red' (modeled as:'red.ledRing.ledController') */
         0U
      }
   },
   /* substruct: esdl_ledController_model_MainClass_RAM.sw (modeled as:'sw.ledController') */
   {
      /* struct element:'esdl_ledController_model_MainClass_RAM.sw.timeCounter' (modeled as:'timeCounter.sw.ledController') */
      0.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'esdl_ledController_model_MainClass_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'esdl_ledController_model_MainClass'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'ledController'
 * data set:.....................................'MODEL_LEDCONTROLLER_STM32F334R8_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct model_LedController_stm32f334r8 esdl_ledController_model_MainClass = {
   /* substruct: esdl_ledController_model_MainClass.sw (modeled as:'sw.ledController') */
   {
      /* type descriptor pointer 'SystemLib_CounterTimer_StopWatch_Automatic_RAM' for memory class substruct for 'RAM' */
      &esdl_ledController_model_MainClass_RAM.sw
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'esdl_ledController_model_MainClass'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: SERAP (definition of data structures)
 * ---------------------------------------------------------------------------*/
/* ----------------------------------------------------------------------------
 * END: SERAP (definition of data structures)
 ******************************************************************************/


#define fadeValue_VAL (esdl_ledController_model_MainClass_RAM.fadeValue)
#define gameState_VAL (esdl_ledController_model_MainClass_RAM.gameState)
#define gameTime_VAL (esdl_ledController_model_MainClass_RAM.gameTime)
#define ledRing_VAL (esdl_ledController_model_MainClass_RAM.ledRing)
#define sm_VAL (esdl_ledController_model_MainClass_RAM.sm)
#define sw_REF (&(esdl_ledController_model_MainClass.sw))

/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/


/* definition of label "IdleFading" from enumeration "model_LedController_enum" */
#define IdleFading 0U
/* definition of label "IndicateGameTime" from enumeration "model_LedController_enum" */
#define IndicateGameTime 1U


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_LedController_stm32f334r8_fadeViolet'
 * ----------------------------------------------------------------------------
 * model name:...................................'fadeViolet'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void model_LedController_stm32f334r8_fadeViolet (void)
{
   /* user defined local variables */
   uint8 i;
   /* temp. variables */
   float32 _t1real32;

   SystemLib_CounterTimer_StopWatch_Automatic_compute(sw_REF);
   if (SystemLib_CounterTimer_StopWatch_Automatic_value(sw_REF) <= 2.0F)
   {
      fadeValue_VAL
         = (SystemLib_CounterTimer_StopWatch_Automatic_value(sw_REF) + 0.2F) / 2.2F;
   }
   else
   {
      if (SystemLib_CounterTimer_StopWatch_Automatic_value(sw_REF) <= 4.0F)
      {
         fadeValue_VAL
            = (4.2F - SystemLib_CounterTimer_StopWatch_Automatic_value(sw_REF)) / 2.2F;
      }
      else
      {
         SystemLib_CounterTimer_StopWatch_Automatic_reset(sw_REF);
      } /* end if */
   } /* end if */
   for (i = 0U;i <= 11U;++i)
   {
      _t1real32 = fadeValue_VAL * 255.0F;
      _t1real32
         = ((_t1real32 < 0.0F) ? (_t1real32 - 0.5F) : (_t1real32 + 0.5F));
      _t1real32
         = ((_t1real32 >= 0.0F) ? (((_t1real32 <= 255.0F) ? _t1real32 : 255.0F)) : 0.0F);
      ledRing_VAL[i].red = (uint8)_t1real32;
      ledRing_VAL[i].green = 0U;
      ledRing_VAL[i].blue = (uint8)_t1real32;
   } /* end for */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_LedController_stm32f334r8_fadeViolet'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_LedController_stm32f334r8_indicateGameTime'
 * ----------------------------------------------------------------------------
 * model name:...................................'indicateGameTime'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void model_LedController_stm32f334r8_indicateGameTime (void)
{
   /* user defined local variables */
   float32 brightness;
   struct model_RgbLed_stm32f334r8 color;
   uint8 i;
   float32 mappedTime;
   /* temp. variables */
   float32 _t1real32;

   color.red = 0U;
   color.green = 0U;
   color.blue = 255U;
   if (gameTime_VAL <= 0.2F)
   {
      color.red = 255U;
      color.green = 0U;
      color.blue = 0U;
   } /* end if */
   mappedTime = gameTime_VAL * 12.0F;
   for (i = 0U;i <= 11U;++i)
   {
      brightness = mappedTime - (float32)i;
      if (brightness > 1.0F)
      {
         brightness = 1.0F;
      } /* end if */
      if (brightness <= 0.0F)
      {
         brightness = 0.0F;
      } /* end if */
      _t1real32 = (float32)color.red * brightness;
      _t1real32
         = ((_t1real32 < 0.0F) ? (_t1real32 - 0.5F) : (_t1real32 + 0.5F));
      ledRing_VAL[i].red
         = ((_t1real32 >= 0.0F) ? (((_t1real32 <= 255.0F) ? (uint8)_t1real32 : 255U)) : 0U);
      _t1real32 = (float32)color.green * brightness;
      _t1real32
         = ((_t1real32 < 0.0F) ? (_t1real32 - 0.5F) : (_t1real32 + 0.5F));
      ledRing_VAL[i].green
         = ((_t1real32 >= 0.0F) ? (((_t1real32 <= 255.0F) ? (uint8)_t1real32 : 255U)) : 0U);
      _t1real32 = (float32)color.blue * brightness;
      _t1real32
         = ((_t1real32 < 0.0F) ? (_t1real32 - 0.5F) : (_t1real32 + 0.5F));
      ledRing_VAL[i].blue
         = ((_t1real32 >= 0.0F) ? (((_t1real32 <= 255.0F) ? (uint8)_t1real32 : 255U)) : 0U);
   } /* end for */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_LedController_stm32f334r8_indicateGameTime'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_LedController_stm32f334r8_isGameIdle'
 * ----------------------------------------------------------------------------
 * model name:...................................'isGameIdle'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_LedController_stm32f334r8_isGameIdle (void)
{
   return gameState_VAL == 0U;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_LedController_stm32f334r8_isGameIdle'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_LedController_stm32f334r8_isGameRunning'
 * ----------------------------------------------------------------------------
 * model name:...................................'isGameRunning'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_LedController_stm32f334r8_isGameRunning (void)
{
   return !model_LedController_stm32f334r8_isGameIdle();
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_LedController_stm32f334r8_isGameRunning'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_LedController_stm32f334r8_periodicTrigger'
 * ----------------------------------------------------------------------------
 * model name:...................................'periodicTrigger'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void model_LedController_stm32f334r8_periodicTrigger (void)
{
   switch (sm_VAL)
   {
      case IndicateGameTime:
         if (model_LedController_stm32f334r8_isGameIdle())
         {
            sm_VAL = IdleFading;
            break;
         } /* end if */
         model_LedController_stm32f334r8_indicateGameTime();
         break;
      case IdleFading:
      default:
         if (model_LedController_stm32f334r8_isGameRunning())
         {
            sm_VAL = IndicateGameTime;
            break;
         } /* end if */
         model_LedController_stm32f334r8_fadeViolet();
         break;
   } /* end switch */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_LedController_stm32f334r8_periodicTrigger'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



