/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0 Hotfix 1
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................model.GameController
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "model_GameController_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a single instance class
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'esdl_gameController_model_MainClass_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'gameController'
 * data set:.....................................'MODEL_GAMECONTROLLER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
__attribute__((section(".ascet_calibration_rom")))
const volatile struct model_GameController_Automatic_CAL_MEM_SUBSTRUCT esdl_gameController_model_MainClass_CAL_MEM = {
   /* struct element:'esdl_gameController_model_MainClass_CAL_MEM.gameTime' (modeled as:'gameTime.gameController') */
   120.0F,
   /* struct element:'esdl_gameController_model_MainClass_CAL_MEM.scoringZone' (modeled as:'scoringZone.gameController') */
   0.2F
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'esdl_gameController_model_MainClass_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'esdl_gameController_model_MainClass_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'gameController'
 * data set:.....................................'MODEL_GAMECONTROLLER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct model_GameController_Automatic_RAM_SUBSTRUCT esdl_gameController_model_MainClass_RAM = {
   /* struct element:'esdl_gameController_model_MainClass_RAM.ballPosition' (modeled as:'ballPosition.gameController') */
   0.0F,
   /* struct element:'esdl_gameController_model_MainClass_RAM.score' (modeled as:'score.gameController') */
   0.0F,
   /* struct element:'esdl_gameController_model_MainClass_RAM.sm' (modeled as:'sm.gameController') */
   0U /* Idle */,
   /* struct element:'esdl_gameController_model_MainClass_RAM.startGame' (modeled as:'startGame.gameController') */
   false,
   /* substruct: esdl_gameController_model_MainClass_RAM.edgeDetect (modeled as:'edgeDetect.gameController') */
   {
      /* struct element:'esdl_gameController_model_MainClass_RAM.edgeDetect.buffer' (modeled as:'buffer.edgeDetect.gameController') */
      false,
      /* struct element:'esdl_gameController_model_MainClass_RAM.edgeDetect.oldSignal' (modeled as:'oldSignal.edgeDetect.gameController') */
      true
   },
   /* substruct: esdl_gameController_model_MainClass_RAM.stopWatch (modeled as:'stopWatch.gameController') */
   {
      /* struct element:'esdl_gameController_model_MainClass_RAM.stopWatch.timeCounter' (modeled as:'timeCounter.stopWatch.gameController') */
      0.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'esdl_gameController_model_MainClass_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'esdl_gameController_model_MainClass'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'gameController'
 * data set:.....................................'MODEL_GAMECONTROLLER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct model_GameController_Automatic esdl_gameController_model_MainClass = {
   /* substruct: esdl_gameController_model_MainClass.edgeDetect (modeled as:'edgeDetect.gameController') */
   {
      /* type descriptor pointer 'SystemLib_Miscellaneous_EdgeRising_Impl_RAM' for memory class substruct for 'RAM' */
      &esdl_gameController_model_MainClass_RAM.edgeDetect
   },
   /* substruct: esdl_gameController_model_MainClass.stopWatch (modeled as:'stopWatch.gameController') */
   {
      /* type descriptor pointer 'SystemLib_CounterTimer_StopWatch_Automatic_RAM' for memory class substruct for 'RAM' */
      &esdl_gameController_model_MainClass_RAM.stopWatch
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'esdl_gameController_model_MainClass'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: SERAP (definition of data structures)
 * ---------------------------------------------------------------------------*/
/* Reference table structure of component 'model_GameController_Automatic' */
const volatile struct PTR_model_GameController_Automatic _SERAP_REF_esdl_gameController_model_MainClass = {
   /* pointer to parameter 'esdl_gameController_model_MainClass_CAL_MEM.gameTime' (modeled as:'gameTime.gameController') */
   &(esdl_gameController_model_MainClass_CAL_MEM.gameTime),
   /* pointer to parameter 'esdl_gameController_model_MainClass_CAL_MEM.scoringZone' (modeled as:'scoringZone.gameController') */
   &(esdl_gameController_model_MainClass_CAL_MEM.scoringZone)
};

/* Working table structure of component 'model_GameController_Automatic' */
const volatile struct PTR_model_GameController_Automatic _SERAP_WORK_esdl_gameController_model_MainClass = {
   /* pointer to parameter 'esdl_gameController_model_MainClass_CAL_MEM.gameTime' (modeled as:'gameTime.gameController') */
   &(esdl_gameController_model_MainClass_CAL_MEM.gameTime),
   /* pointer to parameter 'esdl_gameController_model_MainClass_CAL_MEM.scoringZone' (modeled as:'scoringZone.gameController') */
   &(esdl_gameController_model_MainClass_CAL_MEM.scoringZone)
};
/* ----------------------------------------------------------------------------
 * END: SERAP (definition of data structures)
 ******************************************************************************/


#define ballPosition_VAL (esdl_gameController_model_MainClass_RAM.ballPosition)
#define edgeDetect_REF (&(esdl_gameController_model_MainClass.edgeDetect))
#define gameTime_VAL ((*(USE_PARAM_GLOBAL(float32, _SERAP_REF_esdl_gameController_model_MainClass.gameTime))))
#define score_VAL (esdl_gameController_model_MainClass_RAM.score)
#define scoringZone_VAL ((*(USE_PARAM_GLOBAL(float32, _SERAP_REF_esdl_gameController_model_MainClass.scoringZone))))
#define sm_VAL (esdl_gameController_model_MainClass_RAM.sm)
#define startGame_VAL (esdl_gameController_model_MainClass_RAM.startGame)
#define stopWatch_REF (&(esdl_gameController_model_MainClass.stopWatch))

/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/


/* definition of label "Idle" from enumeration "model_GameController_enum" */
#define Idle 0U
/* definition of label "IncreaseScore" from enumeration "model_GameController_enum" */
#define IncreaseScore 1U
/* definition of label "NotInScoringZone" from enumeration "model_GameController_enum" */
#define NotInScoringZone 2U


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_GameController_Automatic_gameState'
 * ----------------------------------------------------------------------------
 * model name:...................................'gameState'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

uint8 model_GameController_Automatic_gameState (void)
{
   return sm_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_GameController_Automatic_gameState'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_GameController_Automatic_getTime'
 * ----------------------------------------------------------------------------
 * model name:...................................'getTime'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 model_GameController_Automatic_getTime (void)
{
   /* temp. variables */
   float32 _t1real32;

   _t1real32 = SystemLib_CounterTimer_Timer_Automatic_getTime();
   return ((gameTime_VAL == 0.0F) ? _t1real32 : (_t1real32 / gameTime_VAL));
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_GameController_Automatic_getTime'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_GameController_Automatic_isCanceled'
 * ----------------------------------------------------------------------------
 * model name:...................................'isCanceled'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_GameController_Automatic_isCanceled (void)
{
   if ((gameTime_VAL - SystemLib_CounterTimer_Timer_Automatic_getTime()) <= 2.0F)
   {
      return false;
   } /* end if */
   SystemLib_Miscellaneous_EdgeRising_Impl_compute(edgeDetect_REF, startGame_VAL);
   return SystemLib_Miscellaneous_EdgeRising_Impl_value(edgeDetect_REF);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_GameController_Automatic_isCanceled'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_GameController_Automatic_isInScoringZone'
 * ----------------------------------------------------------------------------
 * model name:...................................'isInScoringZone'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_GameController_Automatic_isInScoringZone (void)
{
   /* temp. variables */
   float32 _t1real32;

   _t1real32 = ballPosition_VAL - 0.5F;
   return (((_t1real32 > 0.0F) ? _t1real32 : -_t1real32)) <= (scoringZone_VAL * 0.5F);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_GameController_Automatic_isInScoringZone'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_GameController_Automatic_isStartGameButtonPushed'
 * ----------------------------------------------------------------------------
 * model name:...................................'isStartGameButtonPushed'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_GameController_Automatic_isStartGameButtonPushed (void)
{
   SystemLib_Miscellaneous_EdgeRising_Impl_compute(edgeDetect_REF, startGame_VAL);
   return SystemLib_Miscellaneous_EdgeRising_Impl_value(edgeDetect_REF);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_GameController_Automatic_isStartGameButtonPushed'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_GameController_Automatic_periodicTrigger'
 * ----------------------------------------------------------------------------
 * model name:...................................'periodicTrigger'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void model_GameController_Automatic_periodicTrigger (void)
{
   switch (sm_VAL)
   {
      case IncreaseScore:
         if ((SystemLib_CounterTimer_Timer_Automatic_isElapsed()) || (model_GameController_Automatic_isCanceled()))
         {
            sm_VAL = Idle;
            break;
         } /* end if */
         if (!model_GameController_Automatic_isInScoringZone())
         {
            SystemLib_CounterTimer_Timer_Automatic_compute();
            sm_VAL = NotInScoringZone;
            break;
         } /* end if */
         SystemLib_CounterTimer_StopWatch_Automatic_compute(stopWatch_REF);
         score_VAL
            = SystemLib_CounterTimer_StopWatch_Automatic_value(stopWatch_REF);
         SystemLib_CounterTimer_Timer_Automatic_compute();
         break;
      case NotInScoringZone:
         if ((SystemLib_CounterTimer_Timer_Automatic_isElapsed()) || (model_GameController_Automatic_isCanceled()))
         {
            sm_VAL = Idle;
            break;
         } /* end if */
         if (model_GameController_Automatic_isInScoringZone())
         {
            SystemLib_CounterTimer_Timer_Automatic_compute();
            sm_VAL = IncreaseScore;
            break;
         } /* end if */
         SystemLib_CounterTimer_Timer_Automatic_compute();
         break;
      case Idle:
      default:
         if (model_GameController_Automatic_isStartGameButtonPushed())
         {
            SystemLib_CounterTimer_Timer_Automatic_begin(gameTime_VAL);
            SystemLib_CounterTimer_StopWatch_Automatic_reset(stopWatch_REF);
            score_VAL = 0.0F;
            sm_VAL = NotInScoringZone;
            break;
         } /* end if */
         break;
   } /* end switch */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_GameController_Automatic_periodicTrigger'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



