/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0 Hotfix 1
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................model.ServoController
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "model_ServoController_Automatic.h"
#include "BalanceTube_STMicro_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a single instance class
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'esdl_servoController_model_MainClass_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'servoController'
 * data set:.....................................'MODEL_SERVOCONTROLLER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
__attribute__((section(".ascet_calibration_rom")))
const volatile struct model_ServoController_Automatic_CAL_MEM_SUBSTRUCT esdl_servoController_model_MainClass_CAL_MEM = {
   /* struct element:'esdl_servoController_model_MainClass_CAL_MEM.kd' (modeled as:'kd.servoController') */
   0.03F,
   /* struct element:'esdl_servoController_model_MainClass_CAL_MEM.ki' (modeled as:'ki.servoController') */
   0.22F,
   /* struct element:'esdl_servoController_model_MainClass_CAL_MEM.kp' (modeled as:'kp.servoController') */
   0.22F
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'esdl_servoController_model_MainClass_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'esdl_servoController_model_MainClass_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'servoController'
 * data set:.....................................'MODEL_SERVOCONTROLLER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct model_ServoController_Automatic_RAM_SUBSTRUCT esdl_servoController_model_MainClass_RAM = {
   /* struct element:'esdl_servoController_model_MainClass_RAM.ballPosition' (modeled as:'ballPosition.servoController') */
   0.0F,
   /* struct element:'esdl_servoController_model_MainClass_RAM.error' (modeled as:'error.servoController') */
   0.0F,
   /* struct element:'esdl_servoController_model_MainClass_RAM.handPosition' (modeled as:'handPosition.servoController') */
   0.0F,
   /* struct element:'esdl_servoController_model_MainClass_RAM.integral' (modeled as:'integral.servoController') */
   0.0F,
   /* struct element:'esdl_servoController_model_MainClass_RAM.lastValue' (modeled as:'lastValue.servoController') */
   0.0F,
   /* struct element:'esdl_servoController_model_MainClass_RAM.servoPosition' (modeled as:'servoPosition.servoController') */
   0.0F,
   /* struct element:'esdl_servoController_model_MainClass_RAM.doIntegrate' (modeled as:'doIntegrate.servoController') */
   true,
   /* struct element:'esdl_servoController_model_MainClass_RAM.gameState' (modeled as:'gameState.servoController') */
   0U,
   /* struct element:'esdl_servoController_model_MainClass_RAM.sm' (modeled as:'sm.servoController') */
   0U /* IdlePosition */,
   /* struct element:'esdl_servoController_model_MainClass_RAM.switchMode' (modeled as:'switchMode.servoController') */
   false,
   /* substruct: esdl_servoController_model_MainClass_RAM.edgeDetect (modeled as:'edgeDetect.servoController') */
   {
      /* struct element:'esdl_servoController_model_MainClass_RAM.edgeDetect.buffer' (modeled as:'buffer.edgeDetect.servoController') */
      false,
      /* struct element:'esdl_servoController_model_MainClass_RAM.edgeDetect.oldSignal' (modeled as:'oldSignal.edgeDetect.servoController') */
      true
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'esdl_servoController_model_MainClass_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'esdl_servoController_model_MainClass'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'servoController'
 * data set:.....................................'MODEL_SERVOCONTROLLER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct model_ServoController_Automatic esdl_servoController_model_MainClass = {
   /* substruct: esdl_servoController_model_MainClass.edgeDetect (modeled as:'edgeDetect.servoController') */
   {
      /* type descriptor pointer 'SystemLib_Miscellaneous_EdgeRising_Impl_RAM' for memory class substruct for 'RAM' */
      &esdl_servoController_model_MainClass_RAM.edgeDetect
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'esdl_servoController_model_MainClass'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: SERAP (definition of data structures)
 * ---------------------------------------------------------------------------*/
/* Reference table structure of component 'model_ServoController_Automatic' */
const volatile struct PTR_model_ServoController_Automatic _SERAP_REF_esdl_servoController_model_MainClass = {
   /* pointer to parameter 'esdl_servoController_model_MainClass_CAL_MEM.kd' (modeled as:'kd.servoController') */
   &(esdl_servoController_model_MainClass_CAL_MEM.kd),
   /* pointer to parameter 'esdl_servoController_model_MainClass_CAL_MEM.ki' (modeled as:'ki.servoController') */
   &(esdl_servoController_model_MainClass_CAL_MEM.ki),
   /* pointer to parameter 'esdl_servoController_model_MainClass_CAL_MEM.kp' (modeled as:'kp.servoController') */
   &(esdl_servoController_model_MainClass_CAL_MEM.kp)
};

/* Working table structure of component 'model_ServoController_Automatic' */
const volatile struct PTR_model_ServoController_Automatic _SERAP_WORK_esdl_servoController_model_MainClass = {
   /* pointer to parameter 'esdl_servoController_model_MainClass_CAL_MEM.kd' (modeled as:'kd.servoController') */
   &(esdl_servoController_model_MainClass_CAL_MEM.kd),
   /* pointer to parameter 'esdl_servoController_model_MainClass_CAL_MEM.ki' (modeled as:'ki.servoController') */
   &(esdl_servoController_model_MainClass_CAL_MEM.ki),
   /* pointer to parameter 'esdl_servoController_model_MainClass_CAL_MEM.kp' (modeled as:'kp.servoController') */
   &(esdl_servoController_model_MainClass_CAL_MEM.kp)
};
/* ----------------------------------------------------------------------------
 * END: SERAP (definition of data structures)
 ******************************************************************************/


#define ballPosition_VAL (esdl_servoController_model_MainClass_RAM.ballPosition)
#define doIntegrate_VAL (esdl_servoController_model_MainClass_RAM.doIntegrate)
#define dT_VAL (ASD_DT_SCALED)
#define edgeDetect_REF (&(esdl_servoController_model_MainClass.edgeDetect))
#define error_VAL (esdl_servoController_model_MainClass_RAM.error)
#define gameState_VAL (esdl_servoController_model_MainClass_RAM.gameState)
#define handPosition_VAL (esdl_servoController_model_MainClass_RAM.handPosition)
#define integral_VAL (esdl_servoController_model_MainClass_RAM.integral)
#define kd_VAL ((*(USE_PARAM_GLOBAL(float32, _SERAP_REF_esdl_servoController_model_MainClass.kd))))
#define ki_VAL ((*(USE_PARAM_GLOBAL(float32, _SERAP_REF_esdl_servoController_model_MainClass.ki))))
#define kp_VAL ((*(USE_PARAM_GLOBAL(float32, _SERAP_REF_esdl_servoController_model_MainClass.kp))))
#define lastValue_VAL (esdl_servoController_model_MainClass_RAM.lastValue)
#define servoPosition_VAL (esdl_servoController_model_MainClass_RAM.servoPosition)
#define sm_VAL (esdl_servoController_model_MainClass_RAM.sm)
#define switchMode_VAL (esdl_servoController_model_MainClass_RAM.switchMode)

/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/


/* definition of label "AutoMode" from enumeration "model_ServoController_enum" */
#define AutoMode 1U
/* definition of label "IdlePosition" from enumeration "model_ServoController_enum" */
#define IdlePosition 0U
/* definition of label "ManualMode" from enumeration "model_ServoController_enum" */
#define ManualMode 2U


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_ServoController_Automatic_autoMode'
 * ----------------------------------------------------------------------------
 * model name:...................................'autoMode'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void model_ServoController_Automatic_autoMode (void)
{
   /* temp. variables */
   float32 _t1real32;

   error_VAL = 0.5F - ballPosition_VAL;
   if (doIntegrate_VAL)
   {
      integral_VAL = (ki_VAL * error_VAL * dT_VAL) + integral_VAL;
   } /* end if */
   doIntegrate_VAL = (servoPosition_VAL < 0.9F) && (servoPosition_VAL > 0.1F);
   _t1real32 = (error_VAL - lastValue_VAL) * kd_VAL;
   _t1real32
      = (kp_VAL * error_VAL) + integral_VAL + (((dT_VAL == 0.0F) ? _t1real32 : (_t1real32 / dT_VAL))) + 0.5F;
   servoPosition_VAL
      = ((_t1real32 >= 0.0F) ? (((_t1real32 <= 1.0F) ? _t1real32 : 1.0F)) : 0.0F);
   lastValue_VAL = error_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_ServoController_Automatic_autoMode'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_ServoController_Automatic_isGameIdle'
 * ----------------------------------------------------------------------------
 * model name:...................................'isGameIdle'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_ServoController_Automatic_isGameIdle (void)
{
   return gameState_VAL == 0U;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_ServoController_Automatic_isGameIdle'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_ServoController_Automatic_isGameRunning'
 * ----------------------------------------------------------------------------
 * model name:...................................'isGameRunning'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_ServoController_Automatic_isGameRunning (void)
{
   return !model_ServoController_Automatic_isGameIdle();
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_ServoController_Automatic_isGameRunning'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_ServoController_Automatic_periodicTrigger'
 * ----------------------------------------------------------------------------
 * model name:...................................'periodicTrigger'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void model_ServoController_Automatic_periodicTrigger (void)
{
   switch (sm_VAL)
   {
      case AutoMode:
         if (model_ServoController_Automatic_isGameIdle())
         {
            integral_VAL = 0.0F;
            sm_VAL = IdlePosition;
            break;
         } /* end if */
         if (model_ServoController_Automatic_switchModeButtonPushed())
         {
            integral_VAL = 0.0F;
            sm_VAL = ManualMode;
            break;
         } /* end if */
         model_ServoController_Automatic_autoMode();
         break;
      case ManualMode:
         if (model_ServoController_Automatic_isGameIdle())
         {
            sm_VAL = IdlePosition;
            break;
         } /* end if */
         if (model_ServoController_Automatic_switchModeButtonPushed())
         {
            sm_VAL = AutoMode;
            break;
         } /* end if */
         servoPosition_VAL = handPosition_VAL;
         break;
      case IdlePosition:
      default:
         if (model_ServoController_Automatic_isGameRunning())
         {
            sm_VAL = ManualMode;
            break;
         } /* end if */
         servoPosition_VAL = 0.5F;
         break;
   } /* end switch */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_ServoController_Automatic_periodicTrigger'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_ServoController_Automatic_switchModeButtonPushed'
 * ----------------------------------------------------------------------------
 * model name:...................................'switchModeButtonPushed'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_ServoController_Automatic_switchModeButtonPushed (void)
{
   SystemLib_Miscellaneous_EdgeRising_Impl_compute(edgeDetect_REF, switchMode_VAL);
   return SystemLib_Miscellaneous_EdgeRising_Impl_value(edgeDetect_REF);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_ServoController_Automatic_switchModeButtonPushed'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



