/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0 Hotfix 1
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................model.LedController
 * REPRESENTATION:..............stm32f334r8
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MODEL_LEDCONTROLLER_STM32F334R8_H_
#define _ASD_MODEL_LEDCONTROLLER_STM32F334R8_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "model_RgbLed_stm32f334r8.h"
#include "SystemLib_CounterTimer_StopWatch_Automatic.h"


/* SERAP structure for model_LedController_stm32f334r8 intentionally not created */
/* reason: no local parameters                                                */




/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'model_LedController_stm32f334r8'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct model_LedController_stm32f334r8_RAM_SUBSTRUCT {
   float32 fadeValue;
   float32 gameTime;
   uint8 gameState;
   uint8 sm;
   struct model_RgbLed_stm32f334r8 ledRing[12];
   struct SystemLib_CounterTimer_StopWatch_Automatic_RAM_SUBSTRUCT sw;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'model_LedController_stm32f334r8'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'model_LedController_stm32f334r8'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct model_LedController_stm32f334r8 {
   struct SystemLib_CounterTimer_StopWatch_Automatic sw;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'model_LedController_stm32f334r8'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ............model_LedController_stm32f334r8 */
#define _model_LedController_stm32f334r8_TYPE_DEF_




/* forward declaration of substruct variable 'esdl_ledController_model_MainClass_RAM' */
/* containing 'RAM' memory class tree */
extern struct model_LedController_stm32f334r8_RAM_SUBSTRUCT esdl_ledController_model_MainClass_RAM;

/* forward declaration of component variable 'esdl_ledController_model_MainClass' */
/* containing 'ROM' memory class tree */
extern const struct model_LedController_stm32f334r8 esdl_ledController_model_MainClass;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by class model_LedController_stm32f334r8
 ******************************************************************************/
void model_LedController_stm32f334r8_fadeViolet (void);
void model_LedController_stm32f334r8_indicateGameTime (void);
boolean model_LedController_stm32f334r8_isGameIdle (void);
boolean model_LedController_stm32f334r8_isGameRunning (void);
extern void model_LedController_stm32f334r8_periodicTrigger (void);


/* BEGIN: extern declarations for SERAP */
/* END: extern declarations for SERAP */



#endif /* _ASD_MODEL_LEDCONTROLLER_STM32F334R8_H_ */
