/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0 Hotfix 1
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................model.MainClass
 * REPRESENTATION:..............stm32f334r8
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MODEL_MAINCLASS_STM32F334R8_H_
#define _ASD_MODEL_MAINCLASS_STM32F334R8_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "model_GameController_Automatic.h"
#include "model_LedController_stm32f334r8.h"
#include "model_ServoController_Automatic.h"


/* SERAP structure for model_MainClass_stm32f334r8 intentionally not created  */
/* reason: no local parameters                                                */




/* component structure for module MODEL_MAINCLASS_STM32F334R8 intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ................model_MainClass_stm32f334r8 */
#define _model_MainClass_stm32f334r8_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by module model_MainClass_stm32f334r8
 ******************************************************************************/
extern void model_MainClass_stm32f334r8_step (void);


/* BEGIN: extern declarations for SERAP */
/* END: extern declarations for SERAP */



#endif /* _ASD_MODEL_MAINCLASS_STM32F334R8_H_ */
