/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0 Hotfix 1
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................model.GameController
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_MODEL_GAMECONTROLLER_AUTOMATIC_H_
#define _ASD_MODEL_GAMECONTROLLER_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "SystemLib_CounterTimer_StopWatch_Automatic.h"
#include "SystemLib_CounterTimer_Timer_Automatic.h"
#include "SystemLib_Miscellaneous_EdgeRising_Impl.h"

/******************************************************************************
 * BEGIN: DEFINITION OF SERAP STRUCT FOR CLASS 'model_GameController_Automatic'
 * ---------------------------------------------------------------------------*/
struct PTR_MODEL_GAMECONTROLLER_AUTOMATIC {
   const volatile float32 * gameTime;
   const volatile float32 * scoringZone;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SERAP STRUCT FOR CLASS 'model_GameController_Automatic'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'model_GameController_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct model_GameController_Automatic_CAL_MEM_SUBSTRUCT {
   float32 gameTime;
   float32 scoringZone;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'model_GameController_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'model_GameController_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct model_GameController_Automatic_RAM_SUBSTRUCT {
   float32 ballPosition;
   float32 score;
   uint8 sm;
   boolean startGame;
   struct SystemLib_Miscellaneous_EdgeRising_Impl_RAM_SUBSTRUCT edgeDetect;
   struct SystemLib_CounterTimer_StopWatch_Automatic_RAM_SUBSTRUCT stopWatch;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'model_GameController_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'model_GameController_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct model_GameController_Automatic {
   struct SystemLib_Miscellaneous_EdgeRising_Impl edgeDetect;
   struct SystemLib_CounterTimer_StopWatch_Automatic stopWatch;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'model_GameController_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .............model_GameController_Automatic */
#define _model_GameController_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'esdl_gameController_model_MainClass_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern const volatile struct model_GameController_Automatic_CAL_MEM_SUBSTRUCT esdl_gameController_model_MainClass_CAL_MEM;

/* forward declaration of substruct variable 'esdl_gameController_model_MainClass_RAM' */
/* containing 'RAM' memory class tree */
extern struct model_GameController_Automatic_RAM_SUBSTRUCT esdl_gameController_model_MainClass_RAM;

/* forward declaration of component variable 'esdl_gameController_model_MainClass' */
/* containing 'ROM' memory class tree */
extern const struct model_GameController_Automatic esdl_gameController_model_MainClass;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by class model_GameController_Automatic
 ******************************************************************************/
extern uint8 model_GameController_Automatic_gameState (void);
extern float32 model_GameController_Automatic_getTime (void);
boolean model_GameController_Automatic_isCanceled (void);
boolean model_GameController_Automatic_isInScoringZone (void);
boolean model_GameController_Automatic_isStartGameButtonPushed (void);
extern void model_GameController_Automatic_periodicTrigger (void);


/* BEGIN: extern declarations for SERAP */
extern const volatile struct PTR_model_GameController_Automatic _SERAP_REF_esdl_gameController_model_MainClass;

extern const volatile struct PTR_model_GameController_Automatic _SERAP_WORK_esdl_gameController_model_MainClass;

/* END: extern declarations for SERAP */



#endif /* _ASD_MODEL_GAMECONTROLLER_AUTOMATIC_H_ */
