/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0 Hotfix 1
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................SystemLib.Miscellaneous.DeltaTimeService
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Provides the delta time variable
 ******************************************************************************/
#ifndef _ASD_SYSTEMLIB_MISCELLANEOUS_DELTATIMESERVICE_AUTOMATIC_H_
#define _ASD_SYSTEMLIB_MISCELLANEOUS_DELTATIMESERVICE_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/* SERAP structure for SystemLib_Miscellaneous_DeltaTimeService_Automatic intentionally not created */
/* reason: no local parameters                                                */




/* component structure for module SYSTEMLIB_MISCELLANEOUS_DELTATIMESERVICE_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: SystemLib_Miscellaneous_DeltaTimeService_Automatic */
#define _SystemLib_Miscellaneous_DeltaTimeService_Automatic_TYPE_DEF_




/* BEGIN: extern declarations for SERAP */
/* END: extern declarations for SERAP */



#endif /* _ASD_SYSTEMLIB_MISCELLANEOUS_DELTATIMESERVICE_AUTOMATIC_H_ */
