/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0 Hotfix 1
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................SystemLib.Miscellaneous.DeltaTimeService
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Provides the delta time variable
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "SystemLib_Miscellaneous_DeltaTimeService_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'SystemLib_Miscellaneous_DeltaTimeService'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: SERAP (definition of data structures)
 * ---------------------------------------------------------------------------*/
/* ----------------------------------------------------------------------------
 * END: SERAP (definition of data structures)
 ******************************************************************************/




/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



