/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0 Hotfix 1
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................SystemLib.CounterTimer.Timer
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Timer decrements the time counter by dT and signals when the time counter has reached zero. It is not retriggerable.
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "SystemLib_CounterTimer_Timer_Automatic.h"
#include "BalanceTube_STMicro_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a single instance class
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'esdl_timer_gameController_model_MainClass_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'timer'
 * data set:.....................................'SYSTEMLIB_COUNTERTIMER_TIMER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct SystemLib_CounterTimer_Timer_Automatic_RAM_SUBSTRUCT esdl_timer_gameController_model_MainClass_RAM = {
   /* struct element:'esdl_timer_gameController_model_MainClass_RAM.timeCounter' (modeled as:'timeCounter.timer') */
   0.0F
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'esdl_timer_gameController_model_MainClass_RAM'
 ******************************************************************************/

/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'timer'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: SERAP (definition of data structures)
 * ---------------------------------------------------------------------------*/
/* ----------------------------------------------------------------------------
 * END: SERAP (definition of data structures)
 ******************************************************************************/


#define dT_VAL (ASD_DT_SCALED)
#define timeCounter_VAL (esdl_timer_gameController_model_MainClass_RAM.timeCounter)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'SystemLib_CounterTimer_Timer_Automatic_begin'
 * ----------------------------------------------------------------------------
 * model name:...................................'begin'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void SystemLib_CounterTimer_Timer_Automatic_begin (/* IN    */ const float32 startTime)
{
   timeCounter_VAL = startTime;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'SystemLib_CounterTimer_Timer_Automatic_begin'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'SystemLib_CounterTimer_Timer_Automatic_compute'
 * ----------------------------------------------------------------------------
 * model name:...................................'compute'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void SystemLib_CounterTimer_Timer_Automatic_compute (void)
{
   timeCounter_VAL
      = ((timeCounter_VAL > dT_VAL) ? (timeCounter_VAL - dT_VAL) : 0.0F);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'SystemLib_CounterTimer_Timer_Automatic_compute'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'SystemLib_CounterTimer_Timer_Automatic_getTime'
 * ----------------------------------------------------------------------------
 * model name:...................................'getTime'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 SystemLib_CounterTimer_Timer_Automatic_getTime (void)
{
   return timeCounter_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'SystemLib_CounterTimer_Timer_Automatic_getTime'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'SystemLib_CounterTimer_Timer_Automatic_isElapsed'
 * ----------------------------------------------------------------------------
 * model name:...................................'isElapsed'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean SystemLib_CounterTimer_Timer_Automatic_isElapsed (void)
{
   return timeCounter_VAL <= 0.0F;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'SystemLib_CounterTimer_Timer_Automatic_isElapsed'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



