/******************************************************************************
 * DISCLAIMER
 * This code has been generated by ASCET-DEVELOPER Community Edition.
 * It shall be used only in projects for non commercial use.
 * See license terms and conditions under https://www.etas.com/en/products/download_center.php.
 ******************************************************************************/

/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER Community Edition 7.9.0 Hotfix 1
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................SystemLib.CounterTimer.StopWatch
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    StopWatch increments the time counter by one dT.
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "SystemLib_CounterTimer_StopWatch_Automatic.h"
#include "BalanceTube_STMicro_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/





/******************************************************************************
 * BEGIN: SERAP (definition of data structures)
 * ---------------------------------------------------------------------------*/
/* ----------------------------------------------------------------------------
 * END: SERAP (definition of data structures)
 ******************************************************************************/


#define dT_VAL (ASD_DT_SCALED)
#define timeCounter_VAL (self->SystemLib_CounterTimer_StopWatch_Automatic_RAM->timeCounter)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'SystemLib_CounterTimer_StopWatch_Automatic_compute'
 * ----------------------------------------------------------------------------
 * model name:...................................'compute'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void SystemLib_CounterTimer_StopWatch_Automatic_compute ( const struct SystemLib_CounterTimer_StopWatch_Automatic * self)
{
   timeCounter_VAL = dT_VAL + timeCounter_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'SystemLib_CounterTimer_StopWatch_Automatic_compute'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'SystemLib_CounterTimer_StopWatch_Automatic_reset'
 * ----------------------------------------------------------------------------
 * model name:...................................'reset'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void SystemLib_CounterTimer_StopWatch_Automatic_reset ( const struct SystemLib_CounterTimer_StopWatch_Automatic * self)
{
   timeCounter_VAL = 0.0F;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'SystemLib_CounterTimer_StopWatch_Automatic_reset'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'SystemLib_CounterTimer_StopWatch_Automatic_value'
 * ----------------------------------------------------------------------------
 * model name:...................................'value'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 SystemLib_CounterTimer_StopWatch_Automatic_value ( const struct SystemLib_CounterTimer_StopWatch_Automatic * self)
{
   return timeCounter_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'SystemLib_CounterTimer_StopWatch_Automatic_value'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



